// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         left: "left",
 *         right: "right",
 *         era: "era"
 *     }
 */
export interface CompareRequest {
  /** Stable username for the first driver. */
  left: string;
  /** Stable username for the second driver. */
  right: string;
  /** Era identifier. */
  era: string;
  /** Canonical track configuration code. */
  track?: string;
  /** Canonical vehicle code. */
  vehicle?: string;
}
