// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lfs_username: "lfs_username"
 *     }
 */
export interface GetPlayerRequest {
  /** Stable LFS account name */
  lfs_username: string;
}
