// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface SearchRequest {
  /** Username or display name search text. */
  q: string;
}
