// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         hotlap: 1000000
 *     }
 */
export interface DownloadRequest {
  /** Hotlap identity */
  hotlap: number;
}
