// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         name: "name"
 *     }
 */
export interface CreatePersonalAccessTokenRequest {
  /** Session CSRF token */
  "X-CSRF-Token": string;
  /** Lifetime from creation, from 1 to 365 days. Defaults to 90. */
  expires_in_days?: number | null;
  /** Human-readable purpose shown in the token list. */
  name: string;
}
