// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         token: 1000000
 *     }
 */
export interface RevokeRequest {
  /** Personal access token identity */
  token: number;
  /** Session CSRF token */
  "X-CSRF-Token": string;
}
