// This file was auto-generated by Fern from our API Definition.

export const ListHotlapsRequestColumn = {
  Submitted: "submitted",
  Driver: "driver",
  Rank: "rank",
  LapTime: "lap_time",
} as const;
export type ListHotlapsRequestColumn =
  (typeof ListHotlapsRequestColumn)[keyof typeof ListHotlapsRequestColumn];
