// This file was auto-generated by Fern from our API Definition.

export const ListHotlapsRequestState = {
  All: "all",
  Unpublished: "unpublished",
  Pending: "pending",
  Valid: "valid",
  Invalid: "invalid",
} as const;
export type ListHotlapsRequestState =
  (typeof ListHotlapsRequestState)[keyof typeof ListHotlapsRequestState];
