-- A chart has one identity, shared by all rankings selecting it.
CREATE TABLE chart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    era_id BIGINT NOT NULL REFERENCES era (id) ON DELETE CASCADE,
    track_id TEXT NOT NULL REFERENCES track (id) ON DELETE RESTRICT,
    vehicle_id TEXT NOT NULL REFERENCES vehicle (id) ON DELETE RESTRICT,
    UNIQUE (era_id, track_id, vehicle_id),
    UNIQUE (era_id, id),
    UNIQUE (id, era_id, track_id, vehicle_id)
);
INSERT INTO chart (era_id, track_id, vehicle_id)
SELECT DISTINCT era_id, track_id, vehicle_id FROM ranking_chart
ORDER BY era_id, track_id, vehicle_id;

ALTER TABLE ranking_chart ADD COLUMN chart_id BIGINT;
UPDATE ranking_chart membership SET chart_id = chart.id FROM chart
WHERE chart.era_id = membership.era_id AND chart.track_id = membership.track_id
  AND chart.vehicle_id = membership.vehicle_id;
ALTER TABLE ranking_chart
    ALTER COLUMN chart_id SET NOT NULL,
    DROP COLUMN track_id,
    DROP COLUMN vehicle_id,
    ADD UNIQUE (ranking_id, chart_id),
    ADD FOREIGN KEY (era_id, chart_id) REFERENCES chart (era_id, id) ON DELETE CASCADE;
CREATE INDEX ranking_chart_chart_idx ON ranking_chart (chart_id);

-- Catalogue membership defines which laps can exist. Object storage GC will
-- remove replay objects belonging to these deleted records.
DELETE FROM hotlap WHERE NOT EXISTS (
    SELECT 1 FROM chart WHERE chart.era_id = hotlap.era_id
      AND chart.track_id = hotlap.track AND chart.vehicle_id = hotlap.vehicle
);
ALTER TABLE hotlap ADD COLUMN chart_id BIGINT;
UPDATE hotlap SET chart_id = chart.id FROM chart
WHERE chart.era_id = hotlap.era_id AND chart.track_id = hotlap.track
  AND chart.vehicle_id = hotlap.vehicle;
-- Keep replay classification fields available, with the FK enforcing that
-- they agree with the chart. Repairs must change them together.
ALTER TABLE hotlap
    ALTER COLUMN chart_id SET NOT NULL,
    ADD FOREIGN KEY (chart_id, era_id, track, vehicle)
        REFERENCES chart (id, era_id, track_id, vehicle_id) ON DELETE CASCADE,
    ADD UNIQUE (chart_id, player_id, id);
CREATE INDEX hotlap_chart_best_idx
    ON hotlap (chart_id, player_id, lap_time_ms, created_at, id) WHERE state = 'valid';

ALTER TABLE hotlap_personal_best ADD COLUMN chart_id BIGINT;
UPDATE hotlap_personal_best pb SET chart_id = hotlap.chart_id
FROM hotlap WHERE hotlap.id = pb.hotlap_id;
ALTER TABLE hotlap_personal_best
    DROP CONSTRAINT hotlap_personal_best_pkey,
    DROP COLUMN era_id,
    DROP COLUMN track,
    DROP COLUMN vehicle,
    ALTER COLUMN chart_id SET NOT NULL,
    ADD PRIMARY KEY (chart_id, player_id),
    ADD FOREIGN KEY (chart_id) REFERENCES chart (id) ON DELETE CASCADE,
    ADD FOREIGN KEY (chart_id, player_id, hotlap_id)
        REFERENCES hotlap (chart_id, player_id, id) ON DELETE CASCADE;
CREATE INDEX hotlap_personal_best_position_idx
    ON hotlap_personal_best (chart_id, position);

ALTER TABLE ranking_chart RENAME TO ranking_chart_membership;
