-- YAML and public URLs use immutable slugs.  Relational references use the
-- generated keys below; keeping these concerns separate avoids propagating
-- user-facing identifiers through hot-path indexes.
ALTER TABLE hotlap DROP CONSTRAINT hotlap_era_fk;
ALTER TABLE player_era_badges DROP CONSTRAINT player_era_badges_era_id_fkey;
ALTER TABLE ranking DROP CONSTRAINT ranking_era_id_fkey;
ALTER TABLE era RENAME COLUMN id TO slug;
ALTER TABLE era ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE era DROP CONSTRAINT era_pkey;
ALTER TABLE era ADD PRIMARY KEY (id);
ALTER TABLE era ALTER COLUMN slug SET NOT NULL;
ALTER TABLE era ALTER COLUMN slug TYPE TEXT COLLATE "C";
ALTER TABLE era ADD CONSTRAINT era_slug_key UNIQUE (slug);

ALTER TABLE ranking ADD COLUMN numeric_era_id BIGINT;
UPDATE ranking SET numeric_era_id = era.id FROM era WHERE era.slug = ranking.era_id;
ALTER TABLE ranking ALTER COLUMN numeric_era_id SET NOT NULL;
ALTER TABLE ranking DROP COLUMN era_id CASCADE;
ALTER TABLE ranking RENAME COLUMN numeric_era_id TO era_id;
ALTER TABLE ranking ADD CONSTRAINT ranking_era_id_fkey FOREIGN KEY (era_id) REFERENCES era (id) ON DELETE CASCADE;
ALTER TABLE ranking RENAME COLUMN id TO slug;
ALTER TABLE ranking ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ranking DROP CONSTRAINT IF EXISTS ranking_pkey CASCADE;
ALTER TABLE ranking ADD PRIMARY KEY (id);
ALTER TABLE ranking ALTER COLUMN slug SET NOT NULL;
ALTER TABLE ranking ALTER COLUMN slug TYPE TEXT COLLATE "C";

-- These two unique keys are both integrity constraints and the indexes used
-- by slug resolution and the numeric composite foreign key respectively.
ALTER TABLE ranking ADD CONSTRAINT ranking_era_slug_key UNIQUE (era_id, slug);
ALTER TABLE ranking ADD CONSTRAINT ranking_era_id_key UNIQUE (era_id, id);

-- ranking_chart is small catalogue state. Rebuilding it is clearer and safer
-- than temporarily weakening its composite foreign key while identifiers are
-- translated.
ALTER TABLE ranking_chart RENAME TO ranking_chart_legacy;
CREATE TABLE ranking_chart (
    era_id BIGINT NOT NULL REFERENCES era (id) ON DELETE CASCADE,
    ranking_id BIGINT NOT NULL,
    position INTEGER NOT NULL CHECK (position >= 0),
    track_id TEXT NOT NULL REFERENCES track (id) ON DELETE RESTRICT,
    vehicle_id TEXT NOT NULL REFERENCES vehicle (id) ON DELETE RESTRICT,
    PRIMARY KEY (ranking_id, position),
    UNIQUE (ranking_id, track_id, vehicle_id),
    FOREIGN KEY (era_id, ranking_id) REFERENCES ranking (era_id, id) ON DELETE CASCADE
);
INSERT INTO ranking_chart (era_id, ranking_id, position, track_id, vehicle_id)
SELECT era.id, ranking.id, chart.position, chart.track_id, chart.vehicle_id
FROM ranking_chart_legacy AS chart
JOIN era ON era.slug = chart.era_id
JOIN ranking ON ranking.era_id = era.id AND ranking.slug = chart.ranking_id;
DROP TABLE ranking_chart_legacy;
CREATE INDEX ranking_chart_pair_idx ON ranking_chart (era_id, track_id, vehicle_id);

ALTER TABLE hotlap ADD COLUMN numeric_era_id BIGINT;
UPDATE hotlap SET numeric_era_id = era.id FROM era WHERE era.slug = hotlap.era_id;
ALTER TABLE hotlap ALTER COLUMN numeric_era_id SET NOT NULL;
ALTER TABLE hotlap DROP COLUMN era_id;
ALTER TABLE hotlap RENAME COLUMN numeric_era_id TO era_id;
ALTER TABLE hotlap ADD CONSTRAINT hotlap_era_fk FOREIGN KEY (era_id) REFERENCES era (id) ON DELETE RESTRICT;

ALTER TABLE player_era_badges ADD COLUMN numeric_era_id BIGINT;
UPDATE player_era_badges SET numeric_era_id = era.id FROM era WHERE era.slug = player_era_badges.era_id;
ALTER TABLE player_era_badges ALTER COLUMN numeric_era_id SET NOT NULL;
ALTER TABLE player_era_badges DROP CONSTRAINT player_era_badges_pkey;
ALTER TABLE player_era_badges DROP COLUMN era_id;
ALTER TABLE player_era_badges RENAME COLUMN numeric_era_id TO era_id;
ALTER TABLE player_era_badges ADD PRIMARY KEY (era_id, player_id);
ALTER TABLE player_era_badges ADD CONSTRAINT player_era_badges_era_id_fkey FOREIGN KEY (era_id) REFERENCES era (id) ON DELETE CASCADE;

-- Rebuild every affected hotlap index after the type conversion. PostgreSQL
-- cannot reuse an index whose leading key changed from TEXT to BIGINT.
DROP INDEX IF EXISTS hotlap_chart_idx;
DROP INDEX IF EXISTS hotlap_valid_era_chart_best_idx;
CREATE INDEX hotlap_chart_idx ON hotlap (era_id, track, vehicle, state);
CREATE INDEX hotlap_valid_era_chart_best_idx
    ON hotlap (era_id, track, vehicle, player_id, lap_time_ms, id)
    WHERE state = 'valid';
CREATE INDEX player_era_badges_player_idx ON player_era_badges (player_id, era_id);
