// This file was auto-generated by Fern from our API Definition.

export const BestRequestColumn = {
  Submitted: "submitted",
  Driver: "driver",
  Rank: "rank",
  LapTime: "lap_time",
} as const;
export type BestRequestColumn =
  (typeof BestRequestColumn)[keyof typeof BestRequestColumn];
