// This file was auto-generated by Fern from our API Definition.

export const BestRequestOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type BestRequestOrder =
  (typeof BestRequestOrder)[keyof typeof BestRequestOrder];
