// This file was auto-generated by Fern from our API Definition.

import { AuthenticationClient } from "./api/resources/authentication/client/Client.js";
import { ChartsClient } from "./api/resources/charts/client/Client.js";
import { CountriesClient } from "./api/resources/countries/client/Client.js";
import { ErasClient } from "./api/resources/eras/client/Client.js";
import { HotlapsClient } from "./api/resources/hotlaps/client/Client.js";
import { PersonalAccessTokensClient } from "./api/resources/personalAccessTokens/client/Client.js";
import { PlayersClient } from "./api/resources/players/client/Client.js";
import { RankingClient } from "./api/resources/ranking/client/Client.js";
import { ReplaysClient } from "./api/resources/replays/client/Client.js";
import { StatsClient } from "./api/resources/stats/client/Client.js";
import { TracksClient } from "./api/resources/tracks/client/Client.js";
import { VehiclesClient } from "./api/resources/vehicles/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import {
  normalizeClientOptionsWithAuth,
  type NormalizedClientOptionsWithAuth,
} from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace LfsplanetApiClient {
  export type Options = BaseClientOptions;

  export interface RequestOptions extends BaseRequestOptions {}
}

export class LfsplanetApiClient {
  protected readonly _options: NormalizedClientOptionsWithAuth<LfsplanetApiClient.Options>;
  protected _players: PlayersClient | undefined;
  protected _countries: CountriesClient | undefined;
  protected _eras: ErasClient | undefined;
  protected _charts: ChartsClient | undefined;
  protected _hotlaps: HotlapsClient | undefined;
  protected _ranking: RankingClient | undefined;
  protected _tracks: TracksClient | undefined;
  protected _vehicles: VehiclesClient | undefined;
  protected _replays: ReplaysClient | undefined;
  protected _authentication: AuthenticationClient | undefined;
  protected _personalAccessTokens: PersonalAccessTokensClient | undefined;
  protected _webhooks: WebhooksClient | undefined;
  protected _stats: StatsClient | undefined;

  constructor(options: LfsplanetApiClient.Options) {
    this._options = normalizeClientOptionsWithAuth(options);
  }

  public get players(): PlayersClient {
    return (this._players ??= new PlayersClient(this._options));
  }

  public get countries(): CountriesClient {
    return (this._countries ??= new CountriesClient(this._options));
  }

  public get eras(): ErasClient {
    return (this._eras ??= new ErasClient(this._options));
  }

  public get charts(): ChartsClient {
    return (this._charts ??= new ChartsClient(this._options));
  }

  public get hotlaps(): HotlapsClient {
    return (this._hotlaps ??= new HotlapsClient(this._options));
  }

  public get ranking(): RankingClient {
    return (this._ranking ??= new RankingClient(this._options));
  }

  public get tracks(): TracksClient {
    return (this._tracks ??= new TracksClient(this._options));
  }

  public get vehicles(): VehiclesClient {
    return (this._vehicles ??= new VehiclesClient(this._options));
  }

  public get replays(): ReplaysClient {
    return (this._replays ??= new ReplaysClient(this._options));
  }

  public get authentication(): AuthenticationClient {
    return (this._authentication ??= new AuthenticationClient(this._options));
  }

  public get personalAccessTokens(): PersonalAccessTokensClient {
    return (this._personalAccessTokens ??= new PersonalAccessTokensClient(
      this._options,
    ));
  }

  public get webhooks(): WebhooksClient {
    return (this._webhooks ??= new WebhooksClient(this._options));
  }

  public get stats(): StatsClient {
    return (this._stats ??= new StatsClient(this._options));
  }

  /**
   * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
   * This is useful for making requests to endpoints not yet supported in the SDK.
   * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
   *
   * @param {Request | string | URL} input - The URL, path, or Request object.
   * @param {RequestInit} init - Standard fetch RequestInit options.
   * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
   * @returns {Promise<Response>} A standard Response object.
   */
  public async fetch(
    input: Request | string | URL,
    init?: RequestInit,
    requestOptions?: core.PassthroughRequest.RequestOptions,
  ): Promise<Response> {
    return core.makePassthroughRequest(
      input,
      init,
      {
        baseUrl: this._options.baseUrl ?? this._options.environment,
        headers: this._options.headers,
        timeoutInSeconds: this._options.timeoutInSeconds,
        maxRetries: this._options.maxRetries,
        fetch: this._options.fetch,
        logging: this._options.logging,
        getAuthHeaders: async () =>
          (await this._options.authProvider.getAuthRequest()).headers,
      },
      requestOptions,
    );
  }
}
