// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * An offered competition identified by its era, track and vehicle.
 * Player progress and leaderboard results belong to the surrounding response.
 */
export interface Chart {
  era_id: LfsplanetApi.EraSlug;
  era_title: string;
  track: LfsplanetApi.TrackSummary;
  vehicle: LfsplanetApi.VehicleSummary;
}
