// This file was auto-generated by Fern from our API Definition.

/**
 * A catalogue code and display name. Country codes are ISO alpha-2; flag codes identify display flags.
 */
export interface CodeNameSummary {
  code: string;
  name: string;
}
