// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Whether an era offers a pair, and the resolved chart when it does.
 */
export interface CombinationCheck {
  chart: LfsplanetApi.Chart | null;
  reason: LfsplanetApi.CombinationRejection | null;
  valid: boolean;
}
