// This file was auto-generated by Fern from our API Definition.

/** Why an era does not offer a pair. */
export const CombinationRejection = {
  UnknownTrack: "unknown_track",
  OpenConfiguration: "open_configuration",
  UnknownVehicle: "unknown_vehicle",
  NotOffered: "not_offered",
} as const;
export type CombinationRejection =
  (typeof CombinationRejection)[keyof typeof CombinationRejection];
