// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface ComboSpotlightResponse {
  chart: LfsplanetApi.Chart;
  leaders: LfsplanetApi.SpotlightBestResponse[];
  recent_uploads: number;
}
