// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One side of a current personal-best comparison.
 */
export interface ComparedPlayerResponse {
  player: LfsplanetApi.PlayerSummary;
  results: LfsplanetApi.Hotlap[];
}
