// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface CreatedPersonalAccessTokenResponse {
  credential: LfsplanetApi.PersonalAccessTokenResponse;
  /** Full bearer token. It is returned once and cannot be retrieved later. */
  token: string;
}
