// This file was auto-generated by Fern from our API Definition.

export const DeliveryStatus = {
  Pending: "pending",
  Delivered: "delivered",
  Failed: "failed",
} as const;
export type DeliveryStatus =
  (typeof DeliveryStatus)[keyof typeof DeliveryStatus];
