// This file was auto-generated by Fern from our API Definition.

/** Side of the vehicle occupied by the driver. */
export const DriverSide = {
  Left: "left",
  Right: "right",
} as const;
export type DriverSide = (typeof DriverSide)[keyof typeof DriverSide];
