// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface DriverSpotlightResponse {
  player: LfsplanetApi.PlayerSummary;
  recent_personal_bests: number;
}
