// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * An era and the rankings it offers.
 */
export interface EraSummary {
  id: LfsplanetApi.EraSlug;
  open: boolean;
  rankings: LfsplanetApi.RankingSummary[];
  title: string;
  version_requirement: string;
}
