// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Machine-readable error envelope.
 */
export interface ErrorResponse {
  error: LfsplanetApi.ErrorBody;
}
