// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * A hotlap's player, with era badges when they have been loaded.
 */
export interface HotlapPlayer extends LfsplanetApi.PlayerSummary {
  /** Null when badges have not been loaded for this response. */
  badges: LfsplanetApi.PlayerBadge[] | null;
}
