// This file was auto-generated by Fern from our API Definition.

/**
 * Private replay metadata, returned only to the upload owner.
 */
export interface HotlapSubmission {
  error_detail: string | null;
  hlvc_result_code: number | null;
  mod_version: number | null;
  original_filename: string | null;
  raw_vehicle_name: string;
}
