// This file was auto-generated by Fern from our API Definition.

/** Processing and publication state for a hotlap. */
export const HotlapState = {
  Pending: "pending",
  Valid: "valid",
  Invalid: "invalid",
} as const;
export type HotlapState = (typeof HotlapState)[keyof typeof HotlapState];
