// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One hotlap, shared by collections, charts, profiles, comparisons and owner endpoints.
 */
export interface Hotlap {
  abs_enabled: boolean | null;
  automatic_clutch: boolean;
  automatic_gears: boolean;
  axis_clutch: boolean;
  brake_help_enabled: boolean;
  /** Rankings containing this lap's chart; null when membership has not been loaded. */
  contributes_to: LfsplanetApi.RankingContribution[] | null;
  created_at: string;
  distance_to_benchmark_ms: LfsplanetApi.Milliseconds | null;
  distance_to_world_record_ms: LfsplanetApi.Milliseconds | null;
  driver_side: LfsplanetApi.DriverSide;
  /** Public era slug, used in URLs. */
  era_id: LfsplanetApi.EraSlug;
  era_title: string;
  game_version: string;
  id: number;
  lap_time_ms: LfsplanetApi.Milliseconds;
  manual_shifter: boolean | null;
  player: LfsplanetApi.HotlapPlayer;
  /** Current chart position; null when unranked or chart data has not been loaded. */
  position: number | null;
  /** Relative download URL; null when no replay is stored. */
  replay_url: string | null;
  split_1_ms: LfsplanetApi.Milliseconds;
  split_2_ms: LfsplanetApi.Milliseconds;
  split_3_ms: LfsplanetApi.Milliseconds;
  split_4_ms: LfsplanetApi.Milliseconds;
  state: LfsplanetApi.HotlapState;
  steering: LfsplanetApi.SteeringInput;
  submission?: (LfsplanetApi.HotlapSubmission | null) | undefined;
  track: string;
  vehicle: string;
}
