// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Page-paginated representation of one hotlap chart.
 */
export interface HotlapChartResponse
  extends LfsplanetApi.PaginatedResponseHotlap {
  chart: LfsplanetApi.Chart;
  /** Rankings that include this combination */
  contributes_to: LfsplanetApi.RankingContribution[];
}
