// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseEraSummary {
  items: ListResponseEraSummary.Items.Item[];
}

export namespace ListResponseEraSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * An era and the rankings it offers.
     */
    export interface Item {
      id: LfsplanetApi.EraSlug;
      open: boolean;
      rankings: LfsplanetApi.RankingSummary[];
      title: string;
      version_requirement: string;
    }
  }
}
