// This file was auto-generated by Fern from our API Definition.

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponsePlayerSummary {
  items: ListResponsePlayerSummary.Items.Item[];
}

export namespace ListResponsePlayerSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * Public player details shared by API responses.
     */
    export interface Item {
      country_code: string | null;
      display_name: string;
      flag_code: string | null;
      id: number;
      lfs_username: string;
    }
  }
}
