// This file was auto-generated by Fern from our API Definition.

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseCodeNameSummary {
  items: ListResponseCodeNameSummary.Items.Item[];
}

export namespace ListResponseCodeNameSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * A catalogue code and display name. Country codes are ISO alpha-2; flag codes identify display flags.
     */
    export interface Item {
      code: string;
      name: string;
    }
  }
}
