// This file was auto-generated by Fern from our API Definition.

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponsePersonalAccessTokenResponse {
  items: ListResponsePersonalAccessTokenResponse.Items.Item[];
}

export namespace ListResponsePersonalAccessTokenResponse {
  export type Items = Items.Item[];

  export namespace Items {
    export interface Item {
      created_at: string;
      expires_at: string;
      id: number;
      last_used_at: string | null;
      name: string;
      revoked_at: string | null;
      token_hint: string;
    }
  }
}
