// This file was auto-generated by Fern from our API Definition.

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseVehicleSummary {
  items: ListResponseVehicleSummary.Items.Item[];
}

export namespace ListResponseVehicleSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * Metadata for one canonical Live for Speed vehicle.
     */
    export interface Item {
      code: string;
      /** Relative URL of a locally cached vehicle image, when available. */
      image_url: string | null;
      license: string;
      name: string;
    }
  }
}
