// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseWebhookResponse {
  items: ListResponseWebhookResponse.Items.Item[];
}

export namespace ListResponseWebhookResponse {
  export type Items = Items.Item[];

  export namespace Items {
    export interface Item {
      enabled: boolean;
      event_kind: LfsplanetApi.WebhookEventKind;
      format: LfsplanetApi.WebhookFormat;
      id: number;
      name: string;
    }
  }
}
