// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseNationContributionResponse {
  items: ListResponseNationContributionResponse.Items.Item[];
}

export namespace ListResponseNationContributionResponse {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * A player's contribution to a country's score in one ranking.
     */
    export interface Item {
      contributing_charts: number;
      handicap_ms: LfsplanetApi.Milliseconds;
      player: LfsplanetApi.PlayerSummary;
      points: number;
    }
  }
}
