// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseRankingSummary {
  items: ListResponseRankingSummary.Items.Item[];
}

export namespace ListResponseRankingSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * A ranking offered by an era.
     */
    export interface Item {
      description: string;
      id: string;
      my_progress: LfsplanetApi.RankingProgressResponse | null;
      title: string;
    }
  }
}
