// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Common JSON envelope for collection endpoints.
 */
export interface ListResponseTrackSummary {
  items: ListResponseTrackSummary.Items.Item[];
}

export namespace ListResponseTrackSummary {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * Canonical LFS track configuration metadata.
     */
    export interface Item {
      code: string;
      location: LfsplanetApi.TrackLocationSummary;
      name: string;
      open_configuration: boolean;
      reverse: boolean;
    }
  }
}
