// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Stable authentication-state envelope returned to the frontend.
 */
export interface MeResponse {
  /** Whether immediate hotlap validation is enabled for testing. */
  allow_test_validation: boolean;
  /** Whether the current account may submit hotlap uploads. */
  allow_uploads: boolean;
  /** Whether a current player was found. */
  authenticated: boolean;
  /**
   * Token required in `X-CSRF-Token` for state-changing requests. Empty
   * when logged out, because every such request requires authentication.
   */
  csrf_token: string;
  /** Maximum accepted size of one uploaded SPR replay, in bytes. */
  max_spr_upload_bytes: number;
  player: LfsplanetApi.PlayerSummary | null;
}
