// This file was auto-generated by Fern from our API Definition.

/**
 * A signed millisecond count, including negative time gaps and handicaps.
 *
 * SQL and serde use integer milliseconds; display uses `1:31.234` formatting.
 */
export type Milliseconds = number;
