// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * A player's contribution to a country's score in one ranking.
 */
export interface NationContributionResponse {
  contributing_charts: number;
  handicap_ms: LfsplanetApi.Milliseconds;
  player: LfsplanetApi.PlayerSummary;
  points: number;
}
