// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One row in a national points ranking.
 */
export interface NationRankingEntryResponse {
  contributing_charts: number;
  contributing_laps: number;
  country_code: string;
  handicap_ms: LfsplanetApi.Milliseconds;
  points: number;
  position: number;
}
