// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Collection with page navigation and filtered totals.
 */
export interface PaginatedResponseChart {
  items: PaginatedResponseChart.Items.Item[];
  pagination: LfsplanetApi.Pagination;
}

export namespace PaginatedResponseChart {
  export type Items = Items.Item[];

  export namespace Items {
    /**
     * An offered competition identified by its era, track and vehicle.
     * Player progress and leaderboard results belong to the surrounding response.
     */
    export interface Item {
      era_id: LfsplanetApi.EraSlug;
      era_title: string;
      track: LfsplanetApi.TrackSummary;
      vehicle: LfsplanetApi.VehicleSummary;
    }
  }
}
