// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Collection with page navigation and filtered totals.
 */
export interface PaginatedResponseWebhookNotificationResponse {
  items: PaginatedResponseWebhookNotificationResponse.Items.Item[];
  pagination: LfsplanetApi.Pagination;
}

export namespace PaginatedResponseWebhookNotificationResponse {
  export type Items = Items.Item[];

  export namespace Items {
    export interface Item {
      attempt_count: number;
      created_at: string;
      delivered_at: string | null;
      error_detail?: (string | null) | undefined;
      event_kind: LfsplanetApi.WebhookEventKind;
      failed_at: string | null;
      id: number;
      next_attempt_at: string | null;
      status: LfsplanetApi.DeliveryStatus;
      webhook_name: string;
    }
  }
}
