// This file was auto-generated by Fern from our API Definition.

/**
 * Counts describe the filtered collection before pagination.
 */
export interface Pagination {
  page: number;
  per_page: number;
  total_items: number;
  /** Zero for an empty collection. Out-of-range pages return empty items. */
  total_pages: number;
}
