// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Collection with page navigation and filtered totals.
 */
export interface PaginatedResponseWorldRecordHolderResponse {
  items: PaginatedResponseWorldRecordHolderResponse.Items.Item[];
  pagination: LfsplanetApi.Pagination;
}

export namespace PaginatedResponseWorldRecordHolderResponse {
  export type Items = Items.Item[];

  export namespace Items {
    export interface Item {
      player: LfsplanetApi.PlayerSummary;
      /** Competition rank by record count; equal counts share a position. */
      position: number;
      /** Number of eligible charts on which this driver currently ranks first. */
      world_records: number;
    }
  }
}
