// This file was auto-generated by Fern from our API Definition.

export interface PersonalAccessTokenResponse {
  created_at: string;
  expires_at: string;
  id: number;
  last_used_at: string | null;
  name: string;
  revoked_at: string | null;
  token_hint: string;
}
