// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One row in a personal benchmark-handicap ranking.
 */
export interface PersonalRankingEntryResponse {
  badges: LfsplanetApi.PlayerBadge[];
  completed_charts: number;
  /** Sum of lap time minus the configured benchmark for each chart. */
  handicap_ms: LfsplanetApi.Milliseconds;
  player: LfsplanetApi.PlayerSummary;
  position: number;
  total_charts: number;
}
