// This file was auto-generated by Fern from our API Definition.

/**
 * Lifetime totals across all stored physics eras.
 */
export interface PlayerStatsResponse {
  eras: number;
  first_hotlap_at: string | null;
  hotlaps: number;
  latest_hotlap_at: string | null;
  personal_bests: number;
  podiums: number;
  world_records: number;
}
