// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Public profile and competitive record for one LFS account.
 */
export interface PlayerResponse extends LfsplanetApi.PlayerSummary {
  eras: LfsplanetApi.PlayerEraStatsResponse[];
  highlights: LfsplanetApi.Hotlap[];
  stats: LfsplanetApi.PlayerStatsResponse;
}
