// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One era in which the player has a validated lap.
 */
export interface PlayerEraStatsResponse {
  badges: LfsplanetApi.PlayerBadge[];
  first_hotlap_at: string;
  firsts: number;
  hotlaps: number;
  id: LfsplanetApi.EraSlug;
  latest_hotlap_at: string;
  personal_bests: number;
  seconds: number;
  thirds: number;
  title: string;
}
