// This file was auto-generated by Fern from our API Definition.

/**
 * Public player details shared by API responses.
 */
export interface PlayerSummary {
  country_code: string | null;
  display_name: string;
  flag_code: string | null;
  id: number;
  lfs_username: string;
}
