// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Current chart results for two LFS accounts.
 */
export interface PlayerComparisonResponse {
  left: LfsplanetApi.ComparedPlayerResponse;
  right: LfsplanetApi.ComparedPlayerResponse;
}
