// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * A badge currently held by a player in one era.
 */
export type PlayerBadge =
  /**
   * Current position in an era ranking configured to award a badge. */
  | LfsplanetApi.PlayerBadge.Ranking
  /**
   * Every chart in an era ranking has a published result. */
  | LfsplanetApi.PlayerBadge.RankingCompletion
  /**
   * One or more individual-chart podium positions. */
  | LfsplanetApi.PlayerBadge.WorldRecordPodium
  /**
   * One of the era's leading holders of current world records. */
  | LfsplanetApi.PlayerBadge.WorldRecordLeader
  /**
   * Exactly one published hotlap in this era. */
  | LfsplanetApi.PlayerBadge.Newbie;

export namespace PlayerBadge {
  export interface Ranking {
    kind: "ranking";
    label: string;
    ranking_id: string;
    ranking_position: number;
    title: string;
  }

  export interface RankingCompletion {
    kind: "ranking_completion";
    label: string;
    ranking_id: string;
    title: string;
  }

  export interface WorldRecordPodium {
    kind: "world_record_podium";
    firsts: number;
    level: LfsplanetApi.PodiumLevel;
    seconds: number;
    thirds: number;
  }

  export interface WorldRecordLeader {
    kind: "world_record_leader";
    leader_position: number;
    world_records: number;
  }

  export interface Newbie {
    kind: "newbie";
  }
}
