// This file was auto-generated by Fern from our API Definition.

/** The highest individual-chart podium position currently held by a player. */
export const PodiumLevel = {
  Gold: "gold",
  Silver: "silver",
  Bronze: "bronze",
} as const;
export type PodiumLevel = (typeof PodiumLevel)[keyof typeof PodiumLevel];
