// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Standings for one configured ranking instance, with a typed entry collection.
 */
export interface RankingStandingsNationRankingEntryResponse {
  entries: RankingStandingsNationRankingEntryResponse.Entries.Item[];
  id: string;
  title: string;
  total_charts: number;
}

export namespace RankingStandingsNationRankingEntryResponse {
  export type Entries = Entries.Item[];

  export namespace Entries {
    /**
     * One row in a national points ranking.
     */
    export interface Item {
      contributing_charts: number;
      contributing_laps: number;
      country_code: string;
      handicap_ms: LfsplanetApi.Milliseconds;
      points: number;
      position: number;
    }
  }
}
