// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * A ranking offered by an era.
 */
export interface RankingSummary {
  description: string;
  id: string;
  my_progress: LfsplanetApi.RankingProgressResponse | null;
  title: string;
}
