// This file was auto-generated by Fern from our API Definition.

/**
 * Numeric configuration for the one aggregate ranking system.
 */
export interface RankingRules {
  benchmark_percent: number;
  nation_driver_limit: number;
  nation_max_points: number;
}
