// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Complete metadata for one configured ranking instance.
 */
export interface RankingDetailResponse extends LfsplanetApi.RankingSummary {
  charts: LfsplanetApi.RankingChart[];
  rules: LfsplanetApi.RankingRules;
}
