// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * One required track and vehicle combination in a ranking.
 */
export interface RankingChart {
  chart: LfsplanetApi.Chart;
  my_hotlap: LfsplanetApi.Hotlap | null;
}
