// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Standings for one configured ranking instance, with a typed entry collection.
 */
export interface RankingStandingsPersonalRankingEntryResponse {
  entries: RankingStandingsPersonalRankingEntryResponse.Entries.Item[];
  id: string;
  title: string;
  total_charts: number;
}

export namespace RankingStandingsPersonalRankingEntryResponse {
  export type Entries = Entries.Item[];

  export namespace Entries {
    /**
     * One row in a personal benchmark-handicap ranking.
     */
    export interface Item {
      badges: LfsplanetApi.PlayerBadge[];
      completed_charts: number;
      /** Sum of lap time minus the configured benchmark for each chart. */
      handicap_ms: LfsplanetApi.Milliseconds;
      player: LfsplanetApi.PlayerSummary;
      position: number;
      total_charts: number;
    }
  }
}
