// This file was auto-generated by Fern from our API Definition.

/**
 * Completion of the required charts by the signed-in player.
 */
export interface RankingProgressResponse {
  completed_charts: number;
  total_charts: number;
}
