// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface SpotlightBestResponse {
  distance_to_world_record_ms: LfsplanetApi.Milliseconds;
  lap_time_ms: LfsplanetApi.Milliseconds;
  player: LfsplanetApi.PlayerSummary;
  position: number;
}
