// This file was auto-generated by Fern from our API Definition.

/** Steering input derived from the SPR player flags. */
export const SteeringInput = {
  Wheel: "wheel",
  Mouse: "mouse",
  Keyboard: "keyboard",
  KeyboardStabilised: "keyboard_stabilised",
} as const;
export type SteeringInput = (typeof SteeringInput)[keyof typeof SteeringInput];
