// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Stable code and display name for an LFS location.
 */
export interface TrackLocationSummary {
  code: LfsplanetApi.TrackLocation;
  name: string;
}
