// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Canonical LFS track configuration metadata.
 */
export interface TrackSummary {
  code: string;
  location: LfsplanetApi.TrackLocationSummary;
  name: string;
  open_configuration: boolean;
  reverse: boolean;
}
