// This file was auto-generated by Fern from our API Definition.

/**
 * The LFS location a track configuration belongs to.
 *
 * Locations without a dedicated category, such as Autocross, are `Other`.
 */
export const TrackLocation = {
  Bl: "BL",
  So: "SO",
  Fe: "FE",
  Ky: "KY",
  As: "AS",
  We: "WE",
  Ro: "RO",
  Other: "OTHER",
} as const;
export type TrackLocation = (typeof TrackLocation)[keyof typeof TrackLocation];
