// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata for one canonical Live for Speed vehicle.
 */
export interface VehicleSummary {
  code: string;
  /** Relative URL of a locally cached vehicle image, when available. */
  image_url: string | null;
  license: string;
  name: string;
}
