// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface WebhookEventOption {
  description: string;
  label: string;
  value: LfsplanetApi.WebhookEventKind;
}
