// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface WebhookFormatOption {
  label: string;
  url_help: string;
  url_placeholder: string;
  value: LfsplanetApi.WebhookFormat;
}
