// This file was auto-generated by Fern from our API Definition.

/** Auto-generated discriminant enum variants */
export const WebhookEventKind = {
  HotlapValidated: "hotlap_validated",
  WorldRecordSet: "world_record_set",
} as const;
export type WebhookEventKind =
  (typeof WebhookEventKind)[keyof typeof WebhookEventKind];
