// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

/**
 * Available choices come from the same enums accepted by creation.
 */
export interface WebhookOptionsResponse {
  events: LfsplanetApi.WebhookEventOption[];
  formats: LfsplanetApi.WebhookFormatOption[];
}
