// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface WebhookResponse {
  enabled: boolean;
  event_kind: LfsplanetApi.WebhookEventKind;
  format: LfsplanetApi.WebhookFormat;
  id: number;
  name: string;
}
