// This file was auto-generated by Fern from our API Definition.

export const WebhookFormat = {
  Discord: "discord",
} as const;
export type WebhookFormat = (typeof WebhookFormat)[keyof typeof WebhookFormat];
