// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../index.js";

export interface WorldRecordHolderResponse {
  player: LfsplanetApi.PlayerSummary;
  /** Competition rank by record count; equal counts share a position. */
  position: number;
  /** Number of eligible charts on which this driver currently ranks first. */
  world_records: number;
}
