// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../../../../index.js";

/**
 * @example
 *     {
 *         era: "era",
 *         track: "track",
 *         vehicle: "vehicle"
 *     }
 */
export interface BestRequest {
  /** Target era identifier */
  era: string;
  /** Canonical track configuration code */
  track: string;
  /** Canonical vehicle code */
  vehicle: string;
  /** Column to sort by; defaults to rank. Driver uses case-insensitive display name. */
  column?: LfsplanetApi.BestRequestColumn;
  /** Sort direction; defaults to asc. Equal values retain chart rank order. */
  order?: LfsplanetApi.BestRequestOrder;
  /** ISO 3166-1 alpha-2 player country. */
  country?: string;
  /** Controller: wheel, mouse, keyboard, or keyboard_stabilised. */
  controller?: string;
  /** One-based page number; defaults to 1. */
  page?: number;
  /** Results per page, from 1 to 100; defaults to 50. */
  per_page?: number;
}
