// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token"
 *     }
 */
export interface LogoutRequest {
  /** Session CSRF token */
  "X-CSRF-Token": string;
}
