// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token"
 *     }
 */
export interface UpdateMeRequest {
  /** Session CSRF token */
  "X-CSRF-Token": string;
  /** ISO 3166-1 alpha-2 nation code, or null to leave the nation unset. */
  country_code?: string | null;
  /** FlagCDN code. Null uses the country flag; omitted keeps the current choice. */
  flag_code?: string | null;
}
