// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         vehicle: "vehicle"
 *     }
 */
export interface ImageRequest {
  /** Canonical vehicle code */
  vehicle: string;
}
