// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era"
 *     }
 */
export interface ListEraVehiclesRequest {
  /** Era slug */
  era: string;
  /** Restrict suggestions to combinations on this canonical track. */
  track?: string;
  /** Vehicle code or name search text. */
  q?: string;
  /** Maximum number of vehicles to return (1-100). */
  limit?: number;
}
