// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../../../../index.js";

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         event_kind: "hotlap_validated",
 *         format: "discord",
 *         name: "name",
 *         url: "url"
 *     }
 */
export interface CreateWebhookRequest {
  "X-CSRF-Token": string;
  event_kind: LfsplanetApi.WebhookEventKind;
  format: LfsplanetApi.WebhookFormat;
  name: string;
  url: string;
}
