// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         webhook: 1000000,
 *         enabled: true
 *     }
 */
export interface UpdateWebhookRequest {
  webhook: number;
  "X-CSRF-Token": string;
  enabled: boolean;
}
