// This file was auto-generated by Fern from our API Definition.

import * as LfsplanetApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListHotlapsRequest {
  /** Defaults to valid publicly, all with mine=true. Non-valid selections are caller-only. */
  state?: LfsplanetApi.ListHotlapsRequestState;
  /** Public era slug. */
  era_id?: string;
  /** Stable LFS account name (case-insensitive exact match). */
  lfs_username?: string;
  /** LFS track configuration code, for example BL1 or SO4R. */
  track?: string;
  /** Standard vehicle code or six-digit hexadecimal mod identifier. */
  vehicle?: string;
  /** Only current ranked chart personal bests; defaults to false. */
  ranked_only?: boolean;
  /** Only ranked chart personal bests at this position or better. */
  rank?: number;
  /** ISO 3166-1 alpha-2 player country. */
  country?: string;
  /** Controller: wheel, mouse, keyboard, or keyboard_stabilised. */
  controller?: string;
  /** Only the caller's uploaded replays (requires authentication), including management details. */
  mine?: boolean;
  /** Defaults to submitted. Ties use chart rank ascending; unranked ties sort last. */
  column?: LfsplanetApi.ListHotlapsRequestColumn;
  /** Defaults to desc. */
  order?: LfsplanetApi.ListHotlapsRequestOrder;
  /** One-based page number; defaults to 1. */
  page?: number;
  /** Results per page, from 1 to 100; defaults to 50. */
  per_page?: number;
}
