// This file was auto-generated by Fern from our API Definition.

import * as fs from "fs";
import * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         spr: fs.createReadStream("/path/to/your/file"),
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         era: "era"
 *     }
 */
export interface UploadHotlapRequest {
  /** Era the replay is claimed to belong to */
  era: string;
  /** Required with cookie-session authentication */
  "X-CSRF-Token": string;
  /** Non-empty SPR file with a safe `.spr` filename. */
  spr: core.file.Uploadable;
}
