// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-CSRF-Token": "X-CSRF-Token",
 *         hotlap: 1000000
 *     }
 */
export interface ValidateForTestingRequest {
  /** Hotlap identity */
  hotlap: number;
  /** Required with cookie-session authentication */
  "X-CSRF-Token": string;
}
