// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "code"
 *     }
 */
export interface ListCountryFlagsRequest {
  /** ISO alpha-2 country code */
  code: string;
}
