[package]
name = "lfsplanet_lfs"
version = "0.1.0"
edition = "2024"
publish = false
description = "Local Live for Speed runtime integration"

[lib]
bench = false
doctest = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
