// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era",
 *         track: "track",
 *         vehicle: "vehicle"
 *     }
 */
export interface ValidateEraCombinationRequest {
  /** Era slug */
  era: string;
  /** Canonical track configuration code, e.g. `BL1`. */
  track: string;
  /** Canonical vehicle code, e.g. `XFG`. */
  vehicle: string;
}
