// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era"
 *     }
 */
export interface ListEraRankingsRequest {
  /** Era slug */
  era: string;
}
