// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era"
 *     }
 */
export interface ListEraWorldRecordHoldersRequest {
  /** Era slug */
  era: string;
  /** One-based page number; defaults to 1. */
  page?: number;
  /** Results per page, from 1 to 100; defaults to 50. */
  per_page?: number;
}
