// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era",
 *         ranking: "ranking",
 *         country: "country"
 *     }
 */
export interface NationContributionsRequest {
  /** Era slug */
  era: string;
  /** Ranking slug */
  ranking: string;
  /** Country code */
  country: string;
}
