// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era",
 *         ranking: "ranking"
 *     }
 */
export interface NationsRequest {
  /** Target era identifier */
  era: string;
  /** Ranking identifier */
  ranking: string;
}
