// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         era: "era"
 *     }
 */
export interface ListEraTracksRequest {
  /** Era slug */
  era: string;
  /** Restrict tracks to those paired with this canonical vehicle. */
  vehicle?: string;
}
